import 'package:flutter/material.dart';
import '../models/settings_model.dart';

class AppLocalizations {
  final AppLanguage language;

  AppLocalizations(this.language);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(AppLanguage.english);
  }

  static Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Flashcards',
      'welcome_message': 'Welcome to Flashcards App',
      'create_new_pack': 'Create New Pack',
      'enter_pack_name': 'Enter pack name',
      'enter_characters': 'Enter characters (one per line)',
      'cancel': 'Cancel',
      'create': 'Create',
      'cards_to_review': 'Card to review',
      'no_cards_in_pack': 'No cards in this pack',
      'again_button': 'Again',
      'good_button': 'Good',
      'new_pack': 'New Pack',
      'next_card': 'Next Card',
      'settings': 'Settings',
      'theme': 'Theme',
      'language': 'Language',
      'light_mode': 'Light Mode',
      'dark_mode': 'Dark Mode',
      'system_mode': 'System Mode',
      'english': 'English',
      'russian': 'Russian',
      'fill_blanks': 'Fill in the Blanks',
      'no_cards_available': 'No cards available',
      'correct_answer': 'Correct answer',
      'check': 'Check',
      'next': 'Next',
      'flashcards': 'Flashcards',
      'edit_cards': 'Edit Cards',
      'memory_game': 'Memory Game',
      'victory': 'Victory!',
      'found_all_pairs': 'You found all pairs!',
      'play_again': 'Play Again',
      'find_matching_pairs': 'Find matching pairs',
      'edit_flashcard': 'Edit Flashcard',
      'hanzi': 'Character',
      'pinyin': 'Pinyin',
      'translation': 'Translation',
      'save': 'Save',
      'suggested_translation': 'Suggested translation:',
      'translation_error': 'Translation error',
      'required_fields_error': 'Please fill in all required fields',
      'exercises': 'Exercises',
      'translation_service': 'Translation Service',
      'exercise_service': 'Exercise Generation Service',
      'server_settings': 'Server Settings',
      'bkrs_parser': 'BKRS Parser',
      'bkrs_parser_desc': 'Parse translations from BKRS dictionary website',
      'rest_api_bert': 'REST API (Argos+BERT)',
      'rest_api_bert_desc': 'Use local BERT-based server for translations',
      'bert_chinese': 'BERT Chinese WWM',
      'bert_chinese_desc': 'Use local BERT model for generating exercises',
      'deepseek': 'DeepSeek',
      'deepseek_desc': 'Use DeepSeek API for generating exercises',
      'helsinki_translation': 'Helsinki-NLP',
      'helsinki_translation_desc': 'Use server translation with Helsinki-NLP models',
      'gemma3_bert_wwm': 'Gemma3-IT-QAT + BERT-WWM',
      'gemma3_bert_wwm_desc': 'Use server generation with subsequent validation',
      'offline_mode': 'Offline Mode',
      'offline_mode_desc': 'Use local resources only, no server connection',
      'server_address': 'Server Address',
      'test_connection': 'Test Connection',
      'checking_server': 'Checking server connection...',
      'server_connected': 'Server connected successfully',
      'server_error': 'Server connection error',
      'api_keys': 'API Keys',
      'deepseek_api_key': 'DeepSeek API Key',
      'deepseek_api_key_desc': 'Required for DeepSeek API exercises generation',
      'exercise_complexity': 'Exercise Complexity',
      'simple_complexity': 'Simple',
      'simple_complexity_desc': 'Easier exercises with fewer options',
      'normal_complexity': 'Normal',
      'normal_complexity_desc': 'Balanced difficulty for regular practice',
      'complex_complexity': 'Complex',
      'complex_complexity_desc': 'More challenging exercises with additional options',
      'tech': 'Technical',
      'food': 'Food',
      'everyday': 'Everyday',
      'professions': 'Professions',
      'general': 'General',
      'found_in_dictionary': 'Found in local dictionary',
      'no_reverse_translation': 'No translation found',
      'reverse_translation_error': 'Translation error',
      'reverse_translation_success': 'Translation found',
      'Type translation to find Chinese': 'Type translation to find Chinese',
      'srs_quiz': 'SRS Quiz',
      'character_first': 'Character',
      'translation_first': 'Translation',
      'type_translation': 'Type translation',
      'type_character': 'Type character',
      'correct': 'Correct!',
      'incorrect': 'Incorrect',
      'clear_cache': 'Clear Cache',
      'cache_cleared': 'Exercise cache cleared successfully',
      'cache_clear_error': 'Error clearing cache',
      'testing_connection': 'Testing connection...',
      'connection_successful': 'Connection successful',
      'connection_failed': 'Connection failed',
      'connection_error': 'Connection error',
      'server_modules': 'Server modules',
      'translator': 'Translator',
      'validator': 'Validator',
      'available_models': 'Available models',
    },
    'ru': {
      'app_title': 'Карточки',
      'welcome_message': 'Добро пожаловать в приложение Карточки',
      'create_new_pack': 'Создать новый набор',
      'enter_pack_name': 'Введите название набора',
      'enter_characters': 'Введите символы (по одному в строке)',
      'cancel': 'Отмена',
      'create': 'Создать',
      'cards_to_review': 'Карточка для повторения',
      'no_cards_in_pack': 'В этом наборе нет карточек',
      'again_button': 'Снова',
      'good_button': 'Хорошо',
      'new_pack': 'Новый набор',
      'next_card': 'Следующая карточка',
      'settings': 'Настройки',
      'theme': 'Тема',
      'language': 'Язык',
      'light_mode': 'Светлая тема',
      'dark_mode': 'Тёмная тема',
      'system_mode': 'Системная тема',
      'english': 'Английский',
      'russian': 'Русский',
      'fill_blanks': 'Заполните пропуски',
      'no_cards_available': 'Нет доступных карточек',
      'correct_answer': 'Правильный ответ',
      'check': 'Проверить',
      'next': 'Далее',
      'flashcards': 'Карточки',
      'edit_cards': 'Редактировать карточки',
      'memory_game': 'Игра на память',
      'victory': 'Победа!',
      'found_all_pairs': 'Вы нашли все пары!',
      'play_again': 'Играть снова',
      'find_matching_pairs': 'Найдите соответствующие пары',
      'edit_flashcard': 'Редактировать карточку',
      'hanzi': 'Символ',
      'pinyin': 'Пиньинь',
      'translation': 'Перевод',
      'save': 'Сохранить',
      'suggested_translation': 'Предлагаемый перевод:',
      'translation_error': 'Ошибка перевода',
      'required_fields_error': 'Пожалуйста, заполните все обязательные поля',
      'exercises': 'Упражнения',
      'translation_service': 'Сервис перевода',
      'exercise_service': 'Сервис генерации упражнений',
      'server_settings': 'Настройки сервера',
      'bkrs_parser': 'Парсинг БКРС',
      'bkrs_parser_desc': 'Получать переводы с сайта словаря БКРС',
      'rest_api_bert': 'REST API (Argos+BERT)',
      'rest_api_bert_desc': 'Использовать локальный сервер на базе BERT для переводов',
      'bert_chinese': 'BERT Chinese WWM',
      'bert_chinese_desc': 'Использовать локальную модель BERT для создания упражнений',
      'deepseek': 'DeepSeek',
      'deepseek_desc': 'Использовать API DeepSeek для создания упражнений',
      'helsinki_translation': 'Helsinki-NLP',
      'helsinki_translation_desc': 'Использовать серверный перевод с моделями Helsinki-NLP',
      'gemma3_bert_wwm': 'Gemma3-IT-QAT + BERT-WWM',
      'gemma3_bert_wwm_desc': 'Использовать серверную генерацию с последующей валидацией',
      'offline_mode': 'Автономный режим',
      'offline_mode_desc': 'Использовать только локальные ресурсы, без подключения к серверу',
      'server_address': 'Адрес сервера',
      'test_connection': 'Проверить соединение',
      'checking_server': 'Проверка подключения к серверу...',
      'server_connected': 'Сервер успешно подключен',
      'server_error': 'Ошибка подключения к серверу',
      'api_keys': 'API ключи',
      'deepseek_api_key': 'DeepSeek API ключ',
      'deepseek_api_key_desc': 'Необходим для генерации упражнений через DeepSeek API',
      'exercise_complexity': 'Сложность упражнений',
      'simple_complexity': 'Простой',
      'simple_complexity_desc': 'Более лёгкие упражнения с меньшим количеством вариантов',
      'normal_complexity': 'Обычный',
      'normal_complexity_desc': 'Сбалансированная сложность для регулярных тренировок',
      'complex_complexity': 'Сложный',
      'complex_complexity_desc': 'Более сложные упражнения с дополнительными вариантами',
      'tech': 'Технические',
      'food': 'Еда',
      'everyday': 'Повседневные',
      'professions': 'Профессии',
      'general': 'Общие',
      'found_in_dictionary': 'Найдено в локальном словаре',
      'no_reverse_translation': 'Перевод не найден',
      'reverse_translation_error': 'Ошибка перевода',
      'reverse_translation_success': 'Перевод найден',
      'Type translation to find Chinese': 'Введите перевод, чтобы найти китайский',
      'srs_quiz': 'SRS-тренировка',
      'character_first': 'Иероглиф',
      'translation_first': 'Перевод',
      'type_translation': 'Введите перевод',
      'type_character': 'Введите иероглиф',
      'correct': 'Правильно!',
      'incorrect': 'Неправильно',
      'clear_cache': 'Очистить кэш',
      'cache_cleared': 'Кэш упражнений успешно очищен',
      'cache_clear_error': 'Ошибка при очистке кэша',
      'testing_connection': 'Проверка соединения...',
      'connection_successful': 'Соединение установлено',
      'connection_failed': 'Ошибка соединения',
      'connection_error': 'Ошибка подключения',
      'server_modules': 'Модули сервера',
      'translator': 'Переводчик',
      'validator': 'Валидатор',
      'available_models': 'Доступные модели',
    },
  };

  String translate(String key) {
    final languageCode = language == AppLanguage.russian ? 'ru' : 'en';
    return _localizedValues[languageCode]?[key] ?? key;
  }

  static String staticTranslate(AppLanguage language, String key) {
    final languageCode = language == AppLanguage.russian ? 'ru' : 'en';
    return _localizedValues[languageCode]?[key] ?? key;
  }
}

// Extension method for String to easily use translations
extension StringExtension on String {
  String tr(BuildContext context) {
    return AppLocalizations.of(context).translate(this);
  }
} 